### ISSUE TITLE
Submit to Google search console

### ISSUE THREAD

**Issue by jonrkarr** [biosimulations/Biosimulations#338]
Submit sitemaps to Google
- simulators: 
   - [x] https://biosimulators.org/sitemap.xml
   - [x] https://biosimulators.com/sitemap.xml
- [x] dispatch: https://run.biosimulations.org/sitemap.xml
- [x] platform: https://biosimulations.org/sitemap.xml

**Comment by bilalshaikh42** [comment]
biosimulations.org and bisimulations.io have been added to search console. 
They require DNS verification, which is pending.

**Comment by jonrkarr** [comment]
Can be done once #1332 is closed.

**Comment by jonrkarr** [comment]
@bilalshaikh42 the simulators sitemap can now be submitted to Google.

The dispatch sitemap is ready, but the dispatch app needs to re-deployed first.

The platform app can't be submitted until the version at biosimulations.org is updated.
