### ISSUE TITLE
Update readme to reflect monorepo

### ISSUE THREAD

**Issue by bilalshaikh42** [biosimulations/Biosimulations#520]

**Comment by jonrkarr** [comment]
- I briefly described what the repo contains
- Added brief getting started section
- Replaced "Dependencies" section with pointer to compiled summary of third-party licenses

**Comment by jonrkarr** [comment]
The README is basic, but I think this is enough. @bilalshaikh42 can we close this?

**Comment by bilalshaikh42** [comment]
Yes, I removed the references and directions for the old code structure. The new structure can be explained in #975
