### ISSUE TITLE
Icons and assets files have been corrupted

### ISSUE THREAD

**Issue by bilalshaikh42** [biosimulations/Biosimulations#566]
The favicon and files for the service worker, as well as root level icons have been corrupted. 
Should be regenerated from the angular service worker schematic using the svg timeline icons

**Comment by bilalshaikh42** [comment]
The UI library contains a static folder which can hold the icons in common across all apps. 
present in LoginFrontend branch

**Comment by jonrkarr** [comment]
@bilalshaikh42 I think this can be closed. I think everything in the current revision is good now. I don't think we need any additional old files. They can always be accessed from the repo history.

**Comment by bilalshaikh42** [comment]
Yup, this was resolved with the reorganization
